# Generated by Django 3.2.9 on 2021-12-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentUser',
        ),
        migrations.AddField(
            model_name='appointment',
            name='name',
            field=models.CharField(default=True, max_length=80),
        ),
    ]
