# Generated by Django 3.2.9 on 2022-01-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_alter_appointment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='Email', max_length=254),
        ),
    ]
